plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/ClassLength:
  Max: 200
Layout/LineLength:
  Max: 100

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.4
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "bin/**.*"
    - "config/**.*"
    - "config/**/*"
    - "lib/tasks/**.*"
    - "Gemfile"
    - "Rakefile"
    - "**.md"
    - "**.ico"
    - "**.apib"
    - "**.ru"
    - "**.rake"
    - "**.json"
    - "**.png"
